update changelog
sketch7/signalr-client pull request #36
Opened 2019-06-11 18:28 UTC by stephenlautier

2019-06-19 09:21 UTC, claylaut requested changes

2019-06-19 09:21 UTC, claylaut commented on package.json
>    "devDependencies": {
bump version

2019-06-19 09:25 UTC, stephenlautier commented on package.json
>    "devDependencies": {
done

2019-06-19 09:29 UTC, claylaut approved these changes

2019-06-19 11:32 UTC, claylaut requested changes

2019-06-19 11:32 UTC, claylaut commented on .circleci/config.yml
>        - run:
update to `image: circleci/node:12.4.0`

2019-07-25 18:59 UTC, stephenlautier commented on .circleci/config.yml
>        - run:
done

2019-08-20 18:50 UTC, claylaut approved these changes

2019-08-20 18:51 UTC, merged